export const CREATE_PARTY_REQUEST = 'CREATE_PARTY_REQUEST'
export const CREATE_PARTY_REQUEST_SUCCESS = 'CREATE_PARTY_REQUEST_SUCCESS'
export const CREATE_PARTY_REQUEST_ERROR = 'CREATE_PARTY_REQUEST_ERROR'

