export const DISPLAY_PARTIES_REQUEST = 'DISPLAY_PARTIES_REQUEST'
export const DISPLAY_PARTIES_REQUEST_SUCCESS = 'DISPLAY_PARTIES_REQUEST_SUCCESS'
export const DISPLAY_PARTIES_REQUEST_ERROR = 'DISPLAY_PARTIES_REQUEST_ERROR'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_REQUEST_REQUEST_SUCCESS = 'SIGNUP_REQUEST_REQUEST_SUCCESS'
export const SIGNUP_REQUEST_REQUEST_ERROR = 'SIGNUP_REQUEST_REQUEST_ERROR'
