export const PROFILE_REPLACE_OR_CREATE = 'PROFILE_REPLACE_OR_CREATE'
export const PROFILE_REPLACE_OR_CREATE_SUCCESS = 'PROFILE_REPLACE_OR_CREATE_SUCCESS'
export const PROFILE_REPLACE_OR_CREATE_ERROR = 'PROFILE_REPLACE_OR_CREATE_ERROR'

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_ERROR = 'FETCH_USER_PROFILE_ERROR'

export const USER_PROFILE_UPDATE = 'FETCH_USER_UPDATE'

